apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
  labels:
    type: NFS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
   server: x.x.x.x
   path: "/NFS/nfs1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
  labels:
    type: NFS
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
   server: x.x.x.x
   path: "/NFS/nfs2"
